name: check
on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - uses: extractions/setup-just@v3
      - run: just fmt fmt-taytsh lint lint-taytsh subset

  frontend:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - uses: extractions/setup-just@v3
      - run: just test-cli-local
      - run: just test-parse-local
      - run: just test-subset-local
      - run: just test-names-local
      - run: just test-signatures-local
      - run: just test-fields-local
      - run: just test-hierarchy-local
      - run: just test-inference-local
      - run: just test-lowering-local

  typecheck:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - uses: extractions/setup-just@v3
      - run: just test-typecheck-local

  middleend:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - uses: extractions/setup-just@v3
      - run: just test-middleend-local

  codegen:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - uses: extractions/setup-just@v3
      - run: just test-codegen-local

  taytsh:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - uses: extractions/setup-just@v3
      - run: just test-taytsh-local

  check:
    if: always()
    needs: [lint, frontend, typecheck, middleend, codegen, taytsh]
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "${{ needs.lint.result }}" != "success" || "${{ needs.frontend.result }}" != "success" || "${{ needs.typecheck.result }}" != "success" || "${{ needs.middleend.result }}" != "success" || "${{ needs.codegen.result }}" != "success" || "${{ needs.taytsh.result }}" != "success" ]]; then
            exit 1
          fi
